name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Backend - build
        run: docker build -t ghcr.io/${{ github.repository }}/api:sha-${{ github.sha }} backend
      - name: Frontend - build
        run: docker build -t ghcr.io/${{ github.repository }}/web:sha-${{ github.sha }} frontend
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository }}/api:sha-${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/web:sha-${{ github.sha }}
